### ISSUE TITLE
What is the minimum VRAM required to run this?

### ISSUE THREAD

**Issue by ninjasaid2k** [vvictoryuki/FreeDoM#1]
What is the minimum VRAM required to run this? 24 GB?

**Comment by vvictoryuki** [comment]
Thank you for your attention to our work! Considering that our method requires adding the process of solving the gradient in each sampling step, the GPU memory overhead will be higher than the training required methods. In our current experiments, the GPU memory cost for face-related experiments is 12G, for ImageNet-related experiments is 8G, for Stable Diffusion experiments is 17G, and for ControlNet experiments is 20G. There may be room to optimize the memory cost, but we currently have no plans to do so.
