### ISSUE TITLE
Question on Eq. 4

### ISSUE THREAD

**Issue by denkorzh** [vvictoryuki/FreeDoM#3]
Hi, thanks for sharing your results!

I'm afraid I did not really get how you derived Eq. 4: if I'm not mistaken,
∇ p(c ∣ xₜ) = − λ ∇ ℰ (c, xₜ) + λ ∇ 𝔼 [ ℰ (c, xₜ) ],
where the gradient ∇ is w.r.t. xₜ, and the expectation 𝔼 is over p(c ∣ xₜ).

Why have you decided to ignore the second term? Thank you in advance!

**Comment by vvictoryuki** [comment]
Hi, @denkorzh Thanks for your attention!
I get the Eq.4 just considering the Z in Eq.3 is a constant, then we discard this term after computing the $\nabla\_{\mathbf{x}\_t}\log(\cdot)$. 
Could you tell me how you derived this expectation term? Perhaps we can find some better insights from it to help us improve our work! Look forward to your reply:)

**Comment by xjtupanda** [comment]
> Hi, @denkorzh Thanks for your attention! I get the Eq.4 just considering the Z in Eq.3 is a constant, then we discard this term after computing the ∇xtlog(⋅)∇xtlog⁡(⋅)\nabla_{\mathbf{x}_t}\log(\cdot). Could you tell me how you derived this expectation term? Perhaps we can find some better insights from it to help us improve our work! Look forward to your reply:)

Writing the normalizing constant $Z=\int_c exp(-\lambda \mathcal{\epsilon(c, x_t)}) dc$ in expectation form, we have:
$$
Z=\mathbb{E}_{c \in p(c|x_t)} \  [\exp (-\lambda \mathcal{\epsilon(c, x_t)})]
$$
Plugging into $\log p(c|x_t) = -\lambda \mathcal{\epsilon(c, x_t)} - \log(Z)$ and take derivatives on both sides:
$$
\nabla \log p(c|x_t) = -\lambda \nabla \mathcal{\epsilon(c, x_t)} - \frac{\nabla  \mathbb{E} [\exp (-\lambda \mathcal{\epsilon(c, x_t)})]}{Z}
$$
But the term Z, more specifically the $\mathbb{E} [\exp (-\lambda \mathcal{\epsilon(c, x_t)})]$ term, if I don't get it wrong, is a function of $x_t$, so the gradient term should not be discarded?

**Comment by denkorzh** [comment]
@vvictoryuki 
Exactly, as @xjtupanda mentioned above, *Z* is a constant w.r.t. *c* but is a function of *x_t*.

**Comment by vvictoryuki** [comment]
Thank you for pointing out the shortcomings in our work. We will address the relevant inaccuracies in the latest arXiv version.

**Comment by denkorzh** [comment]
The mistake has never been addressed

**Comment by lzhangbj** [comment]
Similar question here. Conventionally, time-travel strategy has three steps
(1) Modify $x_{t-1}$ via operations like guided gradient propagation etc. 
(2) For harmonization and error reduction, we add noise on top of $x_{t-1}$ to obtain $x_t$.
(3) Apply further denoising step on $x_t$ to obtain $x_{t-1}$ 

This was first proposed in 
[1] RePaint: Inpainting using Denoising Diffusion Probabilistic Models, CVPR 2022.
[2] Zero-Shot Image Restoration Using Denoising Diffusion Null-Space Model, ICLR 2023.

However, in your paper, 
(1) Mathematically, we can't obtain equation 5 from equation 1,2,and 4 (as stated in Section 3.3.). 
(2) Empirically, in algorithm 1&2, using gradients computed w.r.t. $x_t$ to linearly update $x_{t-1}$ is also counter-intuitive.
There seems to be some errors to correct in the paper.
