### ISSUE TITLE
A question on Eq.(1) in the paper

### ISSUE THREAD

**Issue by xjtupanda** [vvictoryuki/FreeDoM#4]
Thanks for sharing the great work! I'm not sure where the formula is from, I've checked the cited paper "Denoising diffusion
probabilistic models", which presents a different formulation. It's also different from the Langevin dynamics sampling formula, could you please clarify this?

**Comment by vvictoryuki** [comment]
@xjtupanda Thanks for your attention!
For deriving Eq.1, we first get the SDE sampling formula in a discrete form:
$\mathbf{x}\_{t-1}=\mathbf{x}\_{t}-[f(\mathbf{x}\_t, t)-g^2(t)\nabla\_{\mathbf{x}\_t}\log p(\mathbf{x}\_t)]+g(t)\boldsymbol{\epsilon}$
Then we use the setting of DDPM ($f(\mathbf{x}\_t, t)=-\frac{1}{2}\beta\_t$, $g(t)=\sqrt{\beta\_t}$) to get the Eq.1:
$\mathbf{x}\_{t-1}=(1+\frac{1}{2}\beta\_t)\mathbf{x}\_t+\beta\_t\nabla\_{\mathbf{x}\_t}\log p(\mathbf{x}\_t) + \sqrt{\beta\_t}\boldsymbol{\epsilon}$
[This Chinese video](https://www.bilibili.com/video/BV1814y1n7Eh/) about SDE sampling formula derivation may further help you:)
