### ISSUE TITLE
Is this only for 1.4 or is there a 1.5 version?

### ISSUE THREAD

**Issue by TruthSearcher** [vvictoryuki/FreeDoM#9]

**Comment by vvictoryuki** [comment]
@TruthSearcher Thank you for your interest in our work! Please note that FreeDoM is agnostic to specific checkpoints, meaning that theoretically both SD-v1.4 and SD-v1.5 checkpoints should be compatible. In our experiments, we have only tried the v1.4 checkpoint, but you can download the v1.5 checkpoint and replace it directly. If you have any results based on the SD-v1.5 checkpoint with FreeDoM, feel free to add them to the issue. We can further discuss them!
